<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eileen Ling">
<meta name="dcterms.date" content="2025-05-06">

<title>Poisson Regression Examples – Eileen’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Eileen’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eileen Ling </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 6, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  patents    region  age iscustomer
1       0   Midwest 32.5          0
2       3 Southwest 37.5          0
3       4 Northwest 27.0          1
4       3 Northeast 24.5          0
5       3 Southwest 37.0          0
6       6 Northeast 29.5          1</code></pre>
</div>
</div>
<p>To compare the patent success of firms using Blueprinty’s software versus those that do not, I first look at the histograms for both groups. The histograms show the distribution of patents awarded, with separate colors indicating whether the firm is a customer or not. I also calculate the mean number of patents for both groups. This allows us to compare the average success between software users and non-users and assess whether Blueprinty’s software correlates with higher patent approval rates.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  iscustomer mean_patents
       &lt;int&gt;        &lt;dbl&gt;
1          0         3.47
2          1         4.13</code></pre>
</div>
</div>
<p>The histogram shows that firms using Blueprinty’s software tend to have more patents than non-users. The average number of patents for software users is 4.13, compared to 3.47 for non-users, suggesting that the software may be associated with higher patent success.</p>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
<p>To compare the regions and ages between Blueprinty customers and non-customers, I begin by summarizing the data to see how these variables differ across the two groups. By examining the regional distribution and age, we can gain insights into whether there are systematic differences between customers and non-customers.</p>
<ol type="1">
<li>Compare the regional distribution:</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the Northeast, non-customers (red) significantly outnumber customers (blue), while in the Midwest, customers and non-customers are more balanced. The South has a relatively higher number of non-customers, but the Southwest shows a clear dominance of customers over non-customers.</p>
<p>This suggests that the adoption of Blueprinty’s software is not evenly distributed across regions, with certain regions (like the Southwest) showing a higher proportion of customers, while others (like the Northeast) have more non-customers.</p>
<ol start="2" type="1">
<li>Compare ages:</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  iscustomer mean_age median_age age_range
       &lt;int&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    
1          0     26.1       25.5 9 - 47.5 
2          1     26.9       26.5 10 - 49  </code></pre>
</div>
</div>
<p>Regarding age, the average and median ages for both customers and non-customers are similar, with non-customers having an average age of 26.1 and customers 26.9. The age range is also nearly the same, indicating that age is not a major factor influencing the adoption of Blueprinty’s software.</p>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, I use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. I start by estimating a simple Poisson model via Maximum Likelihood.</p>
<p>The likelihood function for ( Y () ) is given by:</p>
<p><span class="math display">\[
f(Y | \lambda) = \frac{\lambda^Y e^{-\lambda}}{Y!}
\]</span></p>
<p>Where: - ( Y ) is the number of patents awarded to a firm, - lambda is the rate parameter (mean number of patents), and - ( Y! ) is the factorial of ( Y ).</p>
<p>For a sample of independent observations ( Y_1, Y_2, , Y_n ), the likelihood function is the product of the individual likelihoods:</p>
<p><span class="math display">\[
L(\lambda) = \prod_{i=1}^{n} \frac{\lambda^{Y_i} e^{-\lambda}}{Y_i!}
\]</span></p>
<p>Where ( n ) is the number of firms in the sample.</p>
<p>To estimate lambda , we maximize the log-likelihood:</p>
<p><span class="math display">\[
\log L(\lambda) = \sum_{i=1}^{n} \left( Y_i \log \lambda - \lambda - \log(Y_i!) \right)
\]</span></p>
<p>Maximizing the log-likelihood will provide the estimate for lambda, which represents the average number of patents awarded across all firms in the dataset.</p>
<p>I then use this function to calculate the log-likelihood for a given value of 𝜆 in Poisson model and a vector of observed patent counts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the log-likelihood function for the Poisson model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>poisson_loglikelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, Y) {</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the log-likelihood</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  log_likelihood <span class="ot">&lt;-</span> <span class="fu">sum</span>(Y <span class="sc">*</span> <span class="fu">log</span>(lambda) <span class="sc">-</span> lambda <span class="sc">-</span> <span class="fu">log</span>(<span class="fu">factorial</span>(Y)))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return the log-likelihood</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(log_likelihood)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the observed number of patents </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># For demonstration, using a sample set of data</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> data<span class="sc">$</span>patents  </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a range of lambda values</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>lambda_range <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>)  <span class="co"># Range of lambda values from 0.1 to 10</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the log-likelihood for each lambda value</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>log_likelihood_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(lambda_range, <span class="cf">function</span>(lambda) <span class="fu">poisson_loglikelihood</span>(lambda, Y))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the log-likelihood function</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lambda_range, log_likelihood_values, <span class="at">type =</span> <span class="st">"l"</span>, </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Log-Likelihood vs Lambda"</span>, </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Lambda"</span>, </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Log-Likelihood"</span>, </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows the log-likelihood function for different values of𝜆, representing the average number of patents. It increases sharply at first, then levels off and decreases as 𝜆 continues to rise. The peak of the curve indicates the optimal value of 𝜆, which corresponds to the maximum likelihood estimate for the average number of patents awarded.</p>
<p>To find the Maximum Likelihood Estimate (MLE) for 𝜆 in a Poisson distribution, we take the first derivative of the log-likelihood function with respect to 𝜆, set it equal to zero, and solve for 𝜆.</p>
<p>The log-likelihood function is:</p>
<p><span class="math display">\[
\log L(\lambda) = \sum_{i=1}^{n} \left( Y_i \log \lambda - \lambda - \log(Y_i!) \right)
\]</span></p>
<p>Taking the first derivative with respect to 𝜆:</p>
<p><span class="math display">\[
\frac{d}{d\lambda} \log L(\lambda) = \sum_{i=1}^{n} \left( \frac{Y_i}{\lambda} - 1 \right)
\]</span></p>
<p>Setting this equal to zero:</p>
<p><span class="math display">\[
\sum_{i=1}^{n} \left( \frac{Y_i}{\lambda} - 1 \right) = 0
\]</span></p>
<p>Simplifying:</p>
<p><span class="math display">\[
\lambda = \frac{1}{n} \sum_{i=1}^{n} Y_i = \bar{Y}
\]</span></p>
<p>Thus, the MLE for <span class="math inline">\(\lambda\)</span> is the sample mean of the observed values Y , denoted bar_Y. This is consistent with the fact that the mean of a Poisson distribution is <span class="math inline">\(\lambda\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the log-likelihood function for the Poisson model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>poisson_loglikelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, Y) {</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  log_likelihood <span class="ot">&lt;-</span> <span class="fu">sum</span>(Y <span class="sc">*</span> <span class="fu">log</span>(lambda) <span class="sc">-</span> lambda <span class="sc">-</span> <span class="fu">log</span>(<span class="fu">factorial</span>(Y)))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(log_likelihood)  <span class="co"># Return log-likelihood</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the observed number of patents (Y)</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> data<span class="sc">$</span>patents  <span class="co"># Replace 'data$patents' with your actual data column</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Use optim() to find the MLE for lambda using the Brent method</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>mle_result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="dv">1</span>, <span class="at">fn =</span> <span class="cf">function</span>(l) <span class="sc">-</span><span class="fu">poisson_loglikelihood</span>(l, Y),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"Brent"</span>, <span class="at">lower =</span> <span class="fl">0.01</span>, <span class="at">upper =</span> <span class="dv">20</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the MLE for lambda</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>lambda_mle <span class="ot">&lt;-</span> mle_result<span class="sc">$</span>par</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>lambda_mle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.684667</code></pre>
</div>
</div>
<p>The MLE of λ is 3.684667, meaning that the estimated rate of patents awarded per firm over the last 5 years is approximately 3.68.</p>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p>To estimate the MLE vector and the Hessian of the Poisson regression model with covariates using R’s optim() function, and then calculate the standard errors, follow the steps below. We’ll use the Hessian matrix from the optimization result to compute the standard errors of the coefficient estimates.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Term     Estimate     StdError
1       intercept -0.057869390 0.0247676826
2             age  0.111376215 0.0034735079
3          age_sq -0.002175247 0.0000530556
4 regionNortheast  0.001218348 0.0375689502
5 regionNorthwest -0.007435508 0.0489787049
6     regionSouth -0.017080725 0.0486594534
7 regionSouthwest  0.004882447 0.0430424130
8      iscustomer  0.000000000 0.0000000000</code></pre>
</div>
</div>
<p>Then I check my results using R’s glm() function.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Y ~ X, family = poisson(link = "log"))

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.9781  -0.9278  -0.1149   0.5924   5.0424  

Coefficients: (2 not defined because of singularities)
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -0.3843338  0.1820919  -2.111  0.03480 *  
Xintercept               NA         NA      NA       NA    
Xage              0.1407257  0.0138101  10.190  &lt; 2e-16 ***
Xage_sq          -0.0028103  0.0002568 -10.944  &lt; 2e-16 ***
XregionNortheast  0.1121092  0.0417496   2.685  0.00725 ** 
XregionNorthwest -0.0193872  0.0537827  -0.360  0.71849    
XregionSouth      0.0609820  0.0526598   1.158  0.24685    
XregionSouthwest  0.0544801  0.0472012   1.154  0.24841    
Xiscustomer              NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2362.5  on 1499  degrees of freedom
Residual deviance: 2187.8  on 1493  degrees of freedom
AIC: 6574.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Interpret the results:</p>
<p>The Poisson regression model shows the following:</p>
<p>Significant predictors:</p>
<p>Age (Xage) has a positive effect on the outcome, with each additional year increasing the log of the expected count.</p>
<p>Age squared (Xage_sq) has a negative effect, indicating a diminishing relationship as age increases.</p>
<p>Region (Northeast) (XregionNortheast) is significant, suggesting that being in the Northeast increases the expected count.</p>
<p>Insignificant predictors:</p>
<p>Other regions (Northwest, South, Southwest) and customer status (Xiscustomer) are not statistically significant.</p>
<p>Model fit: The model improves on the null model, as indicated by the decrease in deviance, though there’s still room for improvement.</p>
<p>To assess the impact of Blueprinty’s software on patent success, we simulate two scenarios: one where firms do not use the software (X_0, with iscustomer = 0), and one where they do (X_1, with iscustomer = 1). We use the fitted Poisson regression model to predict the number of patents for firms in both scenarios, obtaining y_pred_0 and y_pred_1, respectively.</p>
<p>We then compute the average of this difference. A positive average suggests that using the software increases patent success, while a negative average suggests a decrease. An average close to zero indicates no significant effect.</p>
<p>This method estimates the average impact of Blueprinty’s software on patent success by comparing the predicted outcomes for firms with and without the software.</p>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
<p>Assume the number of reviews is a good proxy for the number of bookings. Perform some exploratory data analysis to get a feel for the data, handle or drop observations with missing values on relevant variables, build one or more models (e.g., a poisson regression model for the number of bookings as proxied by the number of reviews), and interpret model coefficients to describe variation in the number of reviews as a function of the variables provided.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 40,628
Columns: 14
$ X                         &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1…
$ id                        &lt;int&gt; 2515, 2595, 3647, 3831, 4611, 5099, 5107, 51…
$ days                      &lt;int&gt; 3130, 3127, 3050, 3038, 3012, 2981, 2981, 29…
$ last_scraped              &lt;chr&gt; "4/2/2017", "4/2/2017", "4/2/2017", "4/2/201…
$ host_since                &lt;chr&gt; "9/6/2008", "9/9/2008", "11/25/2008", "12/7/…
$ room_type                 &lt;chr&gt; "Private room", "Entire home/apt", "Private …
$ bathrooms                 &lt;dbl&gt; 1, 1, 1, 1, NA, 1, 1, NA, 1, 1, 1, 1, 1, NA,…
$ bedrooms                  &lt;int&gt; 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2,…
$ price                     &lt;int&gt; 59, 230, 150, 89, 39, 212, 250, 60, 129, 79,…
$ number_of_reviews         &lt;int&gt; 150, 20, 0, 116, 93, 60, 60, 50, 53, 329, 11…
$ review_scores_cleanliness &lt;int&gt; 9, 9, NA, 9, 9, 9, 10, 8, 9, 7, 10, 9, 9, 9,…
$ review_scores_location    &lt;int&gt; 9, 10, NA, 9, 8, 9, 9, 9, 10, 10, 10, 9, 10,…
$ review_scores_value       &lt;int&gt; 9, 9, NA, 9, 9, 9, 10, 9, 9, 9, 10, 9, 10, 9…
$ instant_bookable          &lt;chr&gt; "f", "f", "f", "f", "t", "f", "f", "f", "f",…</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       X               id                days       last_scraped      
 Min.   :    1   Min.   :    2515   Min.   :    1   Length:40628      
 1st Qu.:10158   1st Qu.: 4889868   1st Qu.:  542   Class :character  
 Median :20314   Median : 9862878   Median :  996   Mode  :character  
 Mean   :20314   Mean   : 9698889   Mean   : 1102                     
 3rd Qu.:30471   3rd Qu.:14667894   3rd Qu.: 1535                     
 Max.   :40628   Max.   :18009669   Max.   :42828                     
                                                                      
  host_since         room_type           bathrooms        bedrooms     
 Length:40628       Length:40628       Min.   :0.000   Min.   : 0.000  
 Class :character   Class :character   1st Qu.:1.000   1st Qu.: 1.000  
 Mode  :character   Mode  :character   Median :1.000   Median : 1.000  
                                       Mean   :1.125   Mean   : 1.147  
                                       3rd Qu.:1.000   3rd Qu.: 1.000  
                                       Max.   :8.000   Max.   :10.000  
                                       NA's   :160     NA's   :76      
     price         number_of_reviews review_scores_cleanliness
 Min.   :   10.0   Min.   :  0.0     Min.   : 2.000           
 1st Qu.:   70.0   1st Qu.:  1.0     1st Qu.: 9.000           
 Median :  100.0   Median :  4.0     Median :10.000           
 Mean   :  144.8   Mean   : 15.9     Mean   : 9.198           
 3rd Qu.:  170.0   3rd Qu.: 17.0     3rd Qu.:10.000           
 Max.   :10000.0   Max.   :421.0     Max.   :10.000           
                                     NA's   :10195            
 review_scores_location review_scores_value instant_bookable  
 Min.   : 2.000         Min.   : 2.000      Length:40628      
 1st Qu.: 9.000         1st Qu.: 9.000      Class :character  
 Median :10.000         Median :10.000      Mode  :character  
 Mean   : 9.414         Mean   : 9.332                        
 3rd Qu.:10.000         3rd Qu.:10.000                        
 Max.   :10.000         Max.   :10.000                        
 NA's   :10254          NA's   :10256                         </code></pre>
</div>
</div>
<p>Data cleaning:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       X               id                days       last_scraped      
 Min.   :    1   Min.   :    2515   Min.   :    7   Length:30160      
 1st Qu.: 8630   1st Qu.: 4276690   1st Qu.:  584   Class :character  
 Median :18236   Median : 9149028   Median : 1041   Mode  :character  
 Mean   :18679   Mean   : 8978287   Mean   : 1140                     
 3rd Qu.:28532   3rd Qu.:13914758   3rd Qu.: 1592                     
 Max.   :40504   Max.   :17973686   Max.   :42828                     
  host_since                  room_type       bathrooms        bedrooms     
 Length:30160       Entire home/apt:15543   Min.   :0.000   Min.   : 0.000  
 Class :character   Private room   :13773   1st Qu.:1.000   1st Qu.: 1.000  
 Mode  :character   Shared room    :  844   Median :1.000   Median : 1.000  
                                            Mean   :1.122   Mean   : 1.151  
                                            3rd Qu.:1.000   3rd Qu.: 1.000  
                                            Max.   :6.000   Max.   :10.000  
     price         number_of_reviews review_scores_cleanliness
 Min.   :   10.0   Min.   :  1.00    Min.   : 2.000           
 1st Qu.:   70.0   1st Qu.:  3.00    1st Qu.: 9.000           
 Median :  103.0   Median :  8.00    Median :10.000           
 Mean   :  140.2   Mean   : 21.17    Mean   : 9.202           
 3rd Qu.:  169.0   3rd Qu.: 26.00    3rd Qu.:10.000           
 Max.   :10000.0   Max.   :421.00    Max.   :10.000           
 review_scores_location review_scores_value instant_bookable
 Min.   : 2.000         Min.   : 2.000      Min.   :0.0000  
 1st Qu.: 9.000         1st Qu.: 9.000      1st Qu.:0.0000  
 Median :10.000         Median :10.000      Median :0.0000  
 Mean   : 9.415         Mean   : 9.334      Mean   :0.1962  
 3rd Qu.:10.000         3rd Qu.:10.000      3rd Qu.:0.0000  
 Max.   :10.000         Max.   :10.000      Max.   :1.0000  </code></pre>
</div>
</div>
<p>Distribution of Reviews:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Poisson Regression Model:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = number_of_reviews ~ days + price + bedrooms + bathrooms + 
    review_scores_cleanliness + review_scores_location + review_scores_value + 
    instant_bookable + room_type, family = poisson(link = "log"), 
    data = airbnb_processed)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-21.096   -4.804   -3.001    0.961   38.630  

Coefficients:
                            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                3.498e+00  1.609e-02 217.396  &lt; 2e-16 ***
days                       5.072e-05  3.909e-07 129.757  &lt; 2e-16 ***
price                     -1.791e-05  8.327e-06  -2.151 0.031485 *  
bedrooms                   7.409e-02  1.992e-03  37.197  &lt; 2e-16 ***
bathrooms                 -1.177e-01  3.749e-03 -31.394  &lt; 2e-16 ***
review_scores_cleanliness  1.131e-01  1.496e-03  75.611  &lt; 2e-16 ***
review_scores_location    -7.690e-02  1.609e-03 -47.796  &lt; 2e-16 ***
review_scores_value       -9.108e-02  1.804e-03 -50.490  &lt; 2e-16 ***
instant_bookable           3.459e-01  2.890e-03 119.666  &lt; 2e-16 ***
room_typePrivate room     -1.054e-02  2.738e-03  -3.847 0.000119 ***
room_typeShared room      -2.463e-01  8.620e-03 -28.578  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 961626  on 30159  degrees of freedom
Residual deviance: 926886  on 30149  degrees of freedom
AIC: 1048375

Number of Fisher Scoring iterations: 9</code></pre>
</div>
</div>
<p>Conclusion The Poisson regression model provides insights into the factors influencing the number of reviews for Airbnb listings in New York City. Several variables were found to significantly affect the number of reviews:</p>
<p>Days Listed: A positive relationship between the number of days a property has been listed and the number of reviews suggests that longer-listed properties tend to accumulate more reviews.</p>
<p>Price: A negative coefficient for price indicates that higher-priced listings tend to receive fewer reviews, though the effect is relatively small.</p>
<p>Bedrooms and Bathrooms: More bedrooms are associated with more reviews, whereas more bathrooms are linked to fewer reviews, possibly reflecting the impact of property size on review frequency.</p>
<p>Review Scores: Listings with higher cleanliness and location scores are likely to receive more reviews, while lower value scores negatively affect the number of reviews.</p>
<p>Instant Bookable: The instant bookable feature has a strong positive effect on reviews, suggesting that properties with this feature attract more bookings and reviews.</p>
<p>Room Type: Shared rooms show a significant decrease in reviews compared to entire homes or private rooms, implying that room type plays an important role in attracting reviews.</p>
<p>The model’s fit, with a residual deviance of 926,886 and an AIC of 1,048,375, indicates that it explains a substantial portion of the variation in the number of reviews. Most predictors, except for price and room type, are statistically significant, underscoring their importance in determining the number of reviews.</p>
<p>In conclusion, Airbnb hosts can benefit from improving listing duration, cleanliness, location, and offering features like instant booking to increase their number of reviews. Additionally, adjusting price and room type may also have a meaningful impact on review frequency.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>